# Generated by Django 4.2 on 2023-05-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_perros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('tamanio', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Perros',
        ),
        migrations.DeleteModel(
            name='Sos',
        ),
        migrations.RenameField(
            model_name='adopcion',
            old_name='fecha_entrega',
            new_name='fecha_adopcion',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='esta_aprobado',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='adoptante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_perros.adoptante'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='perro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_perros.perro'),
        ),
    ]
