# Generated by Django 4.2.1 on 2023-05-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_perros', '0002_perro_delete_perros_delete_sos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='perro',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='perro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_perros.perro'),
        ),
    ]
