# Generated by Django 4.2.1 on 2023-05-16 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_perros', '0007_adopcion_creador_adoptante_creador_perro_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
